### ISSUE TITLE
Breaking changes not generating a new MAJOR version

### ISSUE THREAD

**Issue by dbaltor** [dwmkerr/java-maven-standard-version-sample#6]
I committed breaking-changing messages as such `git commit -m 'feat!: new api version'`  and `git commit -m "feat: new api" -m " " -m "BREAKING CHANGE"` and the library bumped the MINOR number instead.

**Comment by dwmkerr** [comment]
Hi @dbaltor is your major version `0.x.y`? If so, when you are in a `0.x.y` release, then even major changes are only on the minor version numbers (this is because 0.x releases are expected to change rapidly)

**Comment by dbaltor** [comment]
Gotcha! I've tested it after your clarification and it's working like a charm.

```
06ef2ca (HEAD -> release, tag: v2.0.0) chore(release): 2.0.0
8270b79 feat!: new api version
4632a72 (tag: v1.1.0) chore(release): 1.1.0
```
Thank you very much for the clarification.
If I may, I'd suggest adding this information to your README file.

Congratulations for the great work! 👏

**Comment by dwmkerr** [comment]
Thanks I've updated the README!
